### ISSUE TITLE
exportFormat doesn't work for .csv files

### ISSUE THREAD

**Issue by hpacleb** [yajra/laravel-datatables-export#28]
### Summary of problem or feature request
exportFormat doesn't work for CSV files.

### Code snippet of problem
Blade file
```html
<livewire:export-button :table-id="$dataTable->getTableId()" filename="export.csv" />
```
Datatable file
```php
Column::make('date')->exportFormat('mm/dd/yyyy'),
```
Dumping the raw date column using Model::first()->date
```
2022-02-04 00:00:00
```
In the export file, the date shows
```
44596
```
After checking the source code of the package, the value from the export is equal to
```php
Date::dateTimeToExcel(Carbon::parse(strval(Model::first()->date));
```
--

### System details

- Operating System : macOS Big Sur Version 11.5.2
- PHP Version :  v8.1.8 
- Laravel Version : v9.21.3
- Laravel-DataTables Version : v9.0.0

--

It seems like the package Openspout doesn't support styling for CSV files as seen here.
```php
    /**
     * @return CSVWriter
     */
    private static function createCSVWriter()
    {
        $optionsManager = new CSVOptionsManager();
        $globalFunctionsHelper = new GlobalFunctionsHelper();

        $helperFactory = new HelperFactory();

        return new CSVWriter($optionsManager, $globalFunctionsHelper, $helperFactory);
    }

    /**
     * @return XLSXWriter
     */
    private static function createXLSXWriter()
    {
        $styleBuilder = new StyleBuilder();
        $optionsManager = new XLSXOptionsManager($styleBuilder);
        $globalFunctionsHelper = new GlobalFunctionsHelper();

        $helperFactory = new XLSXHelperFactory();
        $managerFactory = new XLSXManagerFactory(new InternalEntityFactory(), $helperFactory);

        return new XLSXWriter($optionsManager, $globalFunctionsHelper, $helperFactory, $managerFactory);
    }
```
My first thought for a fix for dates was to change the value directly only for csv exports.
```php
$cellValue = $value ? Carbon::parse(strval($value))->format('m/d/Y') : '';
```
[or convert the excel value back to php datetime](https://stackoverflow.com/questions/11119631/excel-date-conversion-using-php-excel) and then using ->format('m/d/Y')

However there are a few issues for this, carbon format strings are also different from excel formats.
| Carbon Format  | Excel Format | Result |
| ------------- | ------------- | ------------- | 
| ->format('m/d/Y')  | ->exportFormat('mm/dd/yyyy') | 02/04/2022 |

For full comparison : 
[Carbon Full Date Format List](https://www.php.net/manual/en/datetime.format.php)
[Excel Full Date Format List](https://support.microsoft.com/en-us/office/format-numbers-as-dates-or-times-418bd3fe-0577-47c8-8caa-b4d30c528309)

Any thoughts?

**Comment by yajra** [comment]
Based on your inputs, then I guess your first thought would be a way to go. Check first the export type that is being requested. You can then manipulate the value if csv, else use formatting for excel. 

We can also try creating another writer specific for CSV if other data types format are affected too. Thanks!

```php
if ($type == 'csv') {
  // writeToCsv with formatted values
} else {
  // writeToExcel with excel formatting
}
```

**Comment by yajra** [comment]
We will not support formatting on CSV for now as the OpenSpout library doesn't support it yet. Please use excel if formatting is required. Thanks!
