### ISSUE TITLE
window._buildUrl is not a function

### ISSUE THREAD

**Issue by challgren** [yajra/laravel-datatables-export#33]
### Summary of problem or feature request

When implementing the laravel-datatables-export button I'm presented with an error when clicking on the export button that states `window._buildUrl is not a function`. I have all the javascripts implemented along with the https://github.com/yajra/laravel-datatables-buttons/blob/master/src/resources/assets/buttons.server-side.js being in the vendor folder.

### Code snippet of problem
Following along with the Usage guide. Nothing really complex as the buttons.server-side.js contains the _buildUrl function but its not scoped to window.

### System details

- Chrome Version 105.0.5195.125 (Official Build) (x86_64)
- Operating System MacOS 12.6
- PHP Version 8.1.1
- Laravel Version 9.31.0
- Laravel-DataTables Version 10.1.3
- Laravel-DataTables-Export Version 0.14.0

**Comment by yajra** [comment]
Thank you for reporting, I was using https://github.com/yajra/laravel-datatables-assets/blob/master/js/buttons/helper.js and overlook this. I will review the implementation or maybe update the docs when I got the chance.

**Comment by challgren** [comment]
Thank you I'll try that.

**Comment by challgren** [comment]
@github-actions please keep open

**Comment by challgren** [comment]
Hi @yajra I was working with @uchajk and he implemented the helper and it seems to work now. I think maybe including the buildurl function in the package maybe helpful.
