### ISSUE TITLE
Component not found phpunit

### ISSUE THREAD

**Issue by uchajk** [yajra/laravel-datatables-export#43]
##
`[2023-01-10 16:25:54] testing.ERROR: Unable to find component: [export-button] {"userId":1,"exception":"[object] (Livewire\\Exceptions\\ComponentNotFoundException(code: 0): Unable to find component: [export-button] at /Users/ucha/www/project/vendor/livewire/livewire/src/LivewireManager.php:75)
[stacktrace]`

I believe the problem is caused by 
`if (! $this->app->runningInConsole()) {
            Livewire::component('export-button', ExportButtonComponent::class);
        }
` in https://github.com/yajra/laravel-datatables-export/blob/master/src/ExportServiceProvider.php

I guess my question is, why only register the component when not running in console?
And if there is a good reason behind it, how would I go about registering the component when running a test?

**Comment by yajra** [comment]
I think that was added to pass the phpstan issue before. 

Anyways, that check should be removed for unit testing. Would you be able to submit a PR for a fix? Thanks!
