### ISSUE TITLE
Call to a member function finished() on null

### ISSUE THREAD

**Issue by firewall004** [yajra/laravel-datatables-export#57]
### Call to a member function finished() on null 

If the URL has already query params, then it is getting error 
`Call to a member function finished() on null`

On debugging found that the `batchJobId` is coming as the html content of the page.

### Code snippet of problem
```
$.get(baseUrl + '?' + params.toString() + '&' + $.param(oTable.ajax.params())).then(function(exportId) {
    $wire.export(exportId)
}).catch(function(error) {
    $wire.exportFinished = true;
    $wire.exporting = false;
    $wire.exportFailed = true;
});
```

### System details

- Operating System - Ubuntu 22.04
- PHP Version - 8.2
- Laravel Version - ^10.10
- Laravel-DataTables Version - ^10.1

**Comment by firewall004** [comment]
I was able to fix the issue by changing `$.get(baseUrl + '?' + params.toString() + '&' ` to `$.get(baseUrl + '&' + params.toString() + '&' `

**Comment by yajra** [comment]
Your `baseUrl` may have a `?` in it. We may need to enhance how the URL was built I guess.

**Comment by firewall004** [comment]
Yes, the baseUrl may have the query params.

Can we use this to add the params

https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/set

---

```
var url = new URL('http://localhost:8000/reports');

var search_params = url.searchParams;
search_params.set('id', '101');
url.search = search_params.toString();
var new_url = url.toString();

console.log(new_url); // http://localhost:8000/reports?id=101
```
```
var url = new URL('http://localhost:8000/reports?user=2');

var search_params = url.searchParams;
search_params.set('id', '101');
url.search = search_params.toString();
var new_url = url.toString();

console.log(new_url); // http://localhost:8000/reports?user=2&id=101
```

**Comment by yajra** [comment]
Yes, we could use that. Please feel free to submit a PR. Thanks!
