### ISSUE TITLE
Error to install laravel-datatables-export with laravel 11

### ISSUE THREAD

**Issue by abedin99** [yajra/laravel-datatables-export#60]
### Summary of problem or feature request

i am trying to install laravel-datatables. but cannot install this package. 

### Code snippet of problem

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yajra/laravel-datatables-export[v10.1.0, ..., v10.1.1] require yajra/laravel-datatables ^10.0 -> satisfiable by yajra/laravel-datatables[v10.0.0, v10.1.0].
    - yajra/laravel-datatables-export[v11.0.0, ..., v11.1.0] require pestphp/pest ^2.34 -> satisfiable by pestphp/pest[v2.34.0, ..., v2.34.7].
    - yajra/laravel-datatables-export v10.0.0 requires livewire/livewire ^2.11.2 -> satisfiable by livewire/livewire[v2.11.2, ..., v2.12.6].
    - yajra/laravel-datatables-export[v0.1.0, ..., v0.6.1] require yajra/laravel-datatables-buttons 4.* -> found yajra/laravel-datatables-buttons[v4.0.0, ..., v4.13.3] but it conflicts with your root composer.json require (^11.0).
    - yajra/laravel-datatables-export[v0.7.0, ..., v0.14.1, v1.0.0, ..., v1.2.0] require yajra/laravel-datatables-buttons 4.*|9.* -> found yajra/laravel-datatables-buttons[v4.0.0, ..., v4.13.3, v9.0.0, ..., v9.1.4] but it conflicts with your root composer.json require (^11.0).
    - yajra/laravel-datatables v10.0.0 requires yajra/laravel-datatables-oracle ^10 -> found yajra/laravel-datatables-oracle[v10.0.0, ..., v10.11.4] but it conflicts with your root composer.json require (^11.1).
    - yajra/laravel-datatables v10.1.0 requires yajra/laravel-datatables-buttons ^10 -> found yajra/laravel-datatables-buttons[v10.0.0, ..., v10.0.9] but it conflicts with your root composer.json require (^11.0).
    - pestphp/pest[v2.33.6, ..., v2.34.0] require phpunit/phpunit ^10.5.10 -> found phpunit/phpunit[10.5.10, ..., 10.5.20] but it conflicts with your root composer.json require (^11.0.1).
    - pestphp/pest v2.34.1 requires phpunit/phpunit ^10.5.11 -> found phpunit/phpunit[10.5.11, ..., 10.5.20] but it conflicts with your root composer.json require (^11.0.1).
    - pestphp/pest v2.34.2 requires phpunit/phpunit ^10.5.12 -> found phpunit/phpunit[10.5.12, ..., 10.5.20] but it conflicts with your root composer.json require (^11.0.1).
    - pestphp/pest[v2.34.3, ..., v2.34.4] require phpunit/phpunit ^10.5.13 -> found phpunit/phpunit[10.5.13, ..., 10.5.20] but it conflicts with your root composer.json require (^11.0.1).
    - pestphp/pest v2.34.5 requires phpunit/phpunit ^10.5.15 -> found phpunit/phpunit[10.5.15, ..., 10.5.20] but it conflicts with your root composer.json require (^11.0.1).
    - pestphp/pest v2.34.6 requires phpunit/phpunit ^10.5.16 -> found phpunit/phpunit[10.5.16, ..., 10.5.20] but it conflicts with your root composer.json require (^11.0.1).
    - pestphp/pest v2.34.7 requires phpunit/phpunit ^10.5.17 -> found phpunit/phpunit[10.5.17, 10.5.18, 10.5.19, 10.5.20] but it conflicts with your root composer.json require (^11.0.1).
    - livewire/livewire[v2.11.0, ..., v2.12.6] require symfony/http-kernel ^5.0|^6.0 -> found symfony/http-kernel[v5.0.0, ..., v5.4.39, v6.0.0, ..., v6.4.7] but the package is fixed to v7.0.7 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires yajra/laravel-datatables-export * -> satisfiable by yajra/laravel-datatables-export[v0.1.0, ..., v0.14.1, v1.0.0, v1.0.1, v1.1.0, v1.2.0, v10.0.0, v10.1.0, v10.1.1, v11.0.0, 
v11.0.1, v11.1.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require yajra/laravel-datatables-export:*" to figure out if any version is installable, or "composer require yajra/laravel-datatables-export:^2.1" if you know which you need.

- Operating System : windows 10
- PHP Version : 8.2.4
- Laravel Version : 11.0.7
- Laravel-DataTables Version : 
        "yajra/laravel-datatables-buttons": "^11.0",
        "yajra/laravel-datatables-html": "^11.2",
        "yajra/laravel-datatables-oracle": "^11.1"

**Comment by yajra** [comment]
Can you try using `composer require yajra/laravel-datatables`? 

Will review the individual installations when I get the chance. Thanks!

**Comment by yogender-kulshrestha** [comment]
To resolve the issue, try the following commands:
composer self-update
composer update
composer require yajra/laravel-datatables-export

**Comment by yajra** [comment]
Released https://github.com/yajra/laravel-datatables-export/pull/61 which I suspect causes the issue. Please confirm, thanks!
