### ISSUE TITLE
PHPSpreadsheet Constant issue

### ISSUE THREAD

**Issue by dhutapratama** [yajra/laravel-datatables-export#65]
### Summary of problem or feature request

![image](https://github.com/user-attachments/assets/4d54b222-c087-461c-aeea-8577c00d096b)
seems that some changes applied to the dependency and broke this package.

### Code snippet of problem

```composer update```

### System details

- CentOS Stream 8
- PHP 8.3
- Laravel ^10.0
- Laravel-DataTables ^10.1

**Comment by yajra** [comment]
You need to republish the config, force update is needed due to CVE issue https://github.com/yajra/laravel-datatables-export/pull/63

```php
php artisan vendor:publish --tag=datatables-export --force
```

**Comment by dhutapratama** [comment]
> You need to republish the config, force update is needed due to CVE issue #63
> 
> ```
> php artisan vendor:publish --tag=datatables-export --force
> ```

thanks, It looks like this will happen again, but in this case because I was using runner, when I did a code update a few hours later, the error suddenly disappeared.

So it looks like it's not this repository that's the problem, but perhaps somewhere else between composer or packagist.
